
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: epimad_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5437}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: epimad_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: ./BACKEND/Dockerfile
    container_name: epimad_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "${BACKEND_HOST_PORT:-8000}:8000"
    volumes:
      - ./entrainement_modele/arima/models:/app/entrainement_modele/arima/models
      - ./entrainement_modele/xgboost/models:/app/entrainement_modele/xgboost/models
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: epimad_frontend
    restart: always
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:80"
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local